
package com.sbs.easymbank.other.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OtherWebService", targetNamespace = "http://other.easymbank.sbs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OtherWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.sbs.easymbank.other.client.Client
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignaletique", targetNamespace = "http://other.easymbank.sbs.com/", className = "com.sbs.easymbank.other.client.GetSignaletique")
    @ResponseWrapper(localName = "getSignaletiqueResponse", targetNamespace = "http://other.easymbank.sbs.com/", className = "com.sbs.easymbank.other.client.GetSignaletiqueResponse")
    @Action(input = "http://other.easymbank.sbs.com/OtherWebService/getSignaletiqueRequest", output = "http://other.easymbank.sbs.com/OtherWebService/getSignaletiqueResponse")
    public Client getSignaletique(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.sbs.easymbank.other.client.PaymentResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payForService", targetNamespace = "http://other.easymbank.sbs.com/", className = "com.sbs.easymbank.other.client.PayForService")
    @ResponseWrapper(localName = "payForServiceResponse", targetNamespace = "http://other.easymbank.sbs.com/", className = "com.sbs.easymbank.other.client.PayForServiceResponse")
    @Action(input = "http://other.easymbank.sbs.com/OtherWebService/payForServiceRequest", output = "http://other.easymbank.sbs.com/OtherWebService/payForServiceResponse")
    public PaymentResponse payForService(
        @WebParam(name = "arg0", targetNamespace = "")
        PaymentRequest arg0);

}
