
package com.banktowallet.b2w.b2w;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IB2WService", targetNamespace = "http://b2w.banktowallet.com/b2w", wsdlLocation = "file:/C:/Users/HP/Documents/NetBeansProjects/NewEASYMBANK/B2WService/src/wsdl/partner.wsdl")
public class IB2WService extends Service{
    private final static URL IB2WSERVICE_WSDL_LOCATION;
    private final static WebServiceException IB2WSERVICE_EXCEPTION;
    private final static QName IB2WSERVICE_QNAME = new QName("http://b2w.banktowallet.com/b2w", "IB2WService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/HP/Documents/NetBeansProjects/NewEASYMBANK/B2WService/src/wsdl/partner.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IB2WSERVICE_WSDL_LOCATION = url;
        IB2WSERVICE_EXCEPTION = e;
    }

    public IB2WService() {
        super(__getWsdlLocation(), IB2WSERVICE_QNAME);
    }

    public IB2WService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IB2WSERVICE_QNAME, features);
    }

    public IB2WService(URL wsdlLocation) {
        super(wsdlLocation, IB2WSERVICE_QNAME);
    }

    public IB2WService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IB2WSERVICE_QNAME, features);
    }

    public IB2WService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IB2WService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns B2WServices
     */
    @WebEndpoint(name = "B2WServicesPort")
    public B2WServices getB2WServicesPort() {
        return super.getPort(new QName("http://b2w.banktowallet.com/b2w", "B2WServicesPort"), B2WServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns B2WServices
     */
    @WebEndpoint(name = "B2WServicesPort")
    public B2WServices getB2WServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://b2w.banktowallet.com/b2w", "B2WServicesPort"), B2WServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IB2WSERVICE_EXCEPTION!= null) {
            throw IB2WSERVICE_EXCEPTION;
        }
        return IB2WSERVICE_WSDL_LOCATION;
    }

}
