
package com.xnett.fasyl.deploy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "XnettService", targetNamespace = "http://deploy.fasyl.xnett.com/", wsdlLocation = "file:/C:/Users/HP/Documents/NetBeansProjects/NewEASYMBANK/B2WService/src/wsdl/Standard.wsdl")
public class XnettService
    extends Service
{

    private final static URL XNETTSERVICE_WSDL_LOCATION;
    private final static WebServiceException XNETTSERVICE_EXCEPTION;
    private final static QName XNETTSERVICE_QNAME = new QName("http://deploy.fasyl.xnett.com/", "XnettService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/HP/Documents/NetBeansProjects/NewEASYMBANK/B2WService/src/wsdl/Standard.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XNETTSERVICE_WSDL_LOCATION = url;
        XNETTSERVICE_EXCEPTION = e;
    }

    public XnettService() {
        super(__getWsdlLocation(), XNETTSERVICE_QNAME);
    }

    public XnettService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XNETTSERVICE_QNAME, features);
    }

    public XnettService(URL wsdlLocation) {
        super(wsdlLocation, XNETTSERVICE_QNAME);
    }

    public XnettService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XNETTSERVICE_QNAME, features);
    }

    public XnettService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XnettService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Xnett
     */
    @WebEndpoint(name = "XnettPort")
    public Xnett getXnettPort() {
        return super.getPort(new QName("http://deploy.fasyl.xnett.com/", "XnettPort"), Xnett.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Xnett
     */
    @WebEndpoint(name = "XnettPort")
    public Xnett getXnettPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://deploy.fasyl.xnett.com/", "XnettPort"), Xnett.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XNETTSERVICE_EXCEPTION!= null) {
            throw XNETTSERVICE_EXCEPTION;
        }
        return XNETTSERVICE_WSDL_LOCATION;
    }

}
