
package com.xnett.fasyl.deploy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Xnett", targetNamespace = "http://deploy.fasyl.xnett.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Xnett {


    /**
     * 
     * @param txtCountryCode
     * @param mydate
     * @param txtAmount
     * @param txtBFName
     * @param txtAccountNumber
     * @param txtAuthNum
     * @param txtCurrency
     * @param txtBLName
     * @param txtBranchCode
     * @param txtBankName
     * @param txtExternal1
     * @param txtExternal2
     * @param txtRefID
     * @return
     *     returns com.xnett.fasyl.deploy.FundTransferMobileToAccountXResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fundTransferMobileToAccount", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferMobileToAccount")
    @ResponseWrapper(localName = "fundTransferMobileToAccountResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferMobileToAccountResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/fundTransferMobileToAccountRequest", output = "http://deploy.fasyl.xnett.com/Xnett/fundTransferMobileToAccountResponse")
    public FundTransferMobileToAccountXResponse fundTransferMobileToAccount(
        @WebParam(name = "txtBankName", targetNamespace = "")
        String txtBankName,
        @WebParam(name = "txtBranchCode", targetNamespace = "")
        String txtBranchCode,
        @WebParam(name = "txtAccountNumber", targetNamespace = "")
        String txtAccountNumber,
        @WebParam(name = "txtBFName", targetNamespace = "")
        String txtBFName,
        @WebParam(name = "txtBLName", targetNamespace = "")
        String txtBLName,
        @WebParam(name = "txtAmount", targetNamespace = "")
        String txtAmount,
        @WebParam(name = "txtCurrency", targetNamespace = "")
        String txtCurrency,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "txtAuthNum", targetNamespace = "")
        String txtAuthNum,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

    /**
     * 
     * @param txtCountryCode
     * @param mydate
     * @param txtAmount
     * @param txtBFName
     * @param txtAccountNumber
     * @param txtAuthNum
     * @param txtCurrency
     * @param txtBLName
     * @param txtBranchCode
     * @param txtBankName
     * @param txtExternal1
     * @param txtExternal2
     * @param txtRefID
     * @return
     *     returns com.xnett.fasyl.deploy.TransactionEnquiryXResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactionEnquiry", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.TransactionEnquiry")
    @ResponseWrapper(localName = "transactionEnquiryResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.TransactionEnquiryResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/transactionEnquiryRequest", output = "http://deploy.fasyl.xnett.com/Xnett/transactionEnquiryResponse")
    public TransactionEnquiryXResponse transactionEnquiry(
        @WebParam(name = "txtBankName", targetNamespace = "")
        String txtBankName,
        @WebParam(name = "txtBranchCode", targetNamespace = "")
        String txtBranchCode,
        @WebParam(name = "txtAccountNumber", targetNamespace = "")
        String txtAccountNumber,
        @WebParam(name = "txtBFName", targetNamespace = "")
        String txtBFName,
        @WebParam(name = "txtBLName", targetNamespace = "")
        String txtBLName,
        @WebParam(name = "txtAmount", targetNamespace = "")
        String txtAmount,
        @WebParam(name = "txtCurrency", targetNamespace = "")
        String txtCurrency,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "txtAuthNum", targetNamespace = "")
        String txtAuthNum,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

    /**
     * 
     * @param txtCountryCode
     * @param mydate
     * @param txtBFName
     * @param txtAccountNumber
     * @param txtAuthNum
     * @param txtBLName
     * @param txtBranchCode
     * @param txtBankName
     * @param txtExternal1
     * @param txtExternal2
     * @param txtRefID
     * @return
     *     returns com.xnett.fasyl.deploy.BalanceEnquiryXResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balanceEnquiry", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.BalanceEnquiry")
    @ResponseWrapper(localName = "balanceEnquiryResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.BalanceEnquiryResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/balanceEnquiryRequest", output = "http://deploy.fasyl.xnett.com/Xnett/balanceEnquiryResponse")
    public BalanceEnquiryXResponse balanceEnquiry(
        @WebParam(name = "txtBankName", targetNamespace = "")
        String txtBankName,
        @WebParam(name = "txtBranchCode", targetNamespace = "")
        String txtBranchCode,
        @WebParam(name = "txtAccountNumber", targetNamespace = "")
        String txtAccountNumber,
        @WebParam(name = "txtBFName", targetNamespace = "")
        String txtBFName,
        @WebParam(name = "txtBLName", targetNamespace = "")
        String txtBLName,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "txtAuthNum", targetNamespace = "")
        String txtAuthNum,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

    /**
     * 
     * @param txtCountryCode
     * @param mydate
     * @param txtAmount
     * @param txtBFName
     * @param txtAccountNumber
     * @param txtAuthNum
     * @param txtCurrency
     * @param txtBLName
     * @param txtBranchCode
     * @param txtBankName
     * @param txtExternal1
     * @param txtExternal2
     * @param txtRefID
     * @return
     *     returns com.xnett.fasyl.deploy.AccountToMobileXResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fundTransferAccountToMobile", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferAccountToMobile")
    @ResponseWrapper(localName = "fundTransferAccountToMobileResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferAccountToMobileResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/fundTransferAccountToMobileRequest", output = "http://deploy.fasyl.xnett.com/Xnett/fundTransferAccountToMobileResponse")
    public AccountToMobileXResponse fundTransferAccountToMobile(
        @WebParam(name = "txtBankName", targetNamespace = "")
        String txtBankName,
        @WebParam(name = "txtBranchCode", targetNamespace = "")
        String txtBranchCode,
        @WebParam(name = "txtAccountNumber", targetNamespace = "")
        String txtAccountNumber,
        @WebParam(name = "txtBFName", targetNamespace = "")
        String txtBFName,
        @WebParam(name = "txtBLName", targetNamespace = "")
        String txtBLName,
        @WebParam(name = "txtAmount", targetNamespace = "")
        String txtAmount,
        @WebParam(name = "txtCurrency", targetNamespace = "")
        String txtCurrency,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "txtAuthNum", targetNamespace = "")
        String txtAuthNum,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

    /**
     * 
     * @param dFName
     * @param cBankName
     * @param dAccountNumber
     * @param txtAmount
     * @param cAccountNumber
     * @param txtCurrency
     * @param txtExternal1
     * @param txtExternal2
     * @param cFName
     * @param txtRefID
     * @param txtCountryCode
     * @param cLName
     * @param mydate
     * @param dBranchCode
     * @param dBankName
     * @param dLName
     * @param cBranchCode
     * @param smsSourceMsisdn
     * @return
     *     returns com.xnett.fasyl.deploy.AccountToAccountXResponse
     */
    @WebMethod(operationName = "FundTransferAccountToAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FundTransferAccountToAccount", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferAccountToAccount")
    @ResponseWrapper(localName = "FundTransferAccountToAccountResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferAccountToAccountResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/FundTransferAccountToAccountRequest", output = "http://deploy.fasyl.xnett.com/Xnett/FundTransferAccountToAccountResponse")
    public AccountToAccountXResponse fundTransferAccountToAccount(
        @WebParam(name = "dBankName", targetNamespace = "")
        String dBankName,
        @WebParam(name = "dBranchCode", targetNamespace = "")
        String dBranchCode,
        @WebParam(name = "dAccountNumber", targetNamespace = "")
        String dAccountNumber,
        @WebParam(name = "dFName", targetNamespace = "")
        String dFName,
        @WebParam(name = "dLName", targetNamespace = "")
        String dLName,
        @WebParam(name = "cBankName", targetNamespace = "")
        String cBankName,
        @WebParam(name = "cBranchCode", targetNamespace = "")
        String cBranchCode,
        @WebParam(name = "cAccountNumber", targetNamespace = "")
        String cAccountNumber,
        @WebParam(name = "cFName", targetNamespace = "")
        String cFName,
        @WebParam(name = "cLName", targetNamespace = "")
        String cLName,
        @WebParam(name = "txtAmount", targetNamespace = "")
        String txtAmount,
        @WebParam(name = "txtCurrency", targetNamespace = "")
        String txtCurrency,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "smsSourceMsisdn", targetNamespace = "")
        String smsSourceMsisdn,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

    /**
     * 
     * @param txtCountryCode
     * @param mydate
     * @param txtAmount
     * @param txtBFName
     * @param txtAccountNumber
     * @param txtAuthNum
     * @param txtCurrency
     * @param txtBLName
     * @param txtBranchCode
     * @param txtBankName
     * @param txtExternal1
     * @param txtExternal2
     * @param txtRefID
     * @return
     *     returns com.xnett.fasyl.deploy.AccountToMobileInquiryXResponse
     */
    @WebMethod(operationName = "FundTransferAccountToMobileInquiry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FundTransferAccountToMobileInquiry", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferAccountToMobileInquiry")
    @ResponseWrapper(localName = "FundTransferAccountToMobileInquiryResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferAccountToMobileInquiryResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/FundTransferAccountToMobileInquiryRequest", output = "http://deploy.fasyl.xnett.com/Xnett/FundTransferAccountToMobileInquiryResponse")
    public AccountToMobileInquiryXResponse fundTransferAccountToMobileInquiry(
        @WebParam(name = "txtBankName", targetNamespace = "")
        String txtBankName,
        @WebParam(name = "txtBranchCode", targetNamespace = "")
        String txtBranchCode,
        @WebParam(name = "txtAccountNumber", targetNamespace = "")
        String txtAccountNumber,
        @WebParam(name = "txtBFName", targetNamespace = "")
        String txtBFName,
        @WebParam(name = "txtBLName", targetNamespace = "")
        String txtBLName,
        @WebParam(name = "txtAmount", targetNamespace = "")
        String txtAmount,
        @WebParam(name = "txtCurrency", targetNamespace = "")
        String txtCurrency,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "txtAuthNum", targetNamespace = "")
        String txtAuthNum,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

    /**
     * 
     * @param txtCountryCode
     * @param mydate
     * @param txtAmount
     * @param txtBFName
     * @param txtAccountNumber
     * @param txtAuthNum
     * @param txtCurrency
     * @param txtBLName
     * @param txtBranchCode
     * @param txtBankName
     * @param txtExternal1
     * @param txtExternal2
     * @param txtRefID
     * @return
     *     returns com.xnett.fasyl.deploy.FundTransferMobileToAccountInquiryXResponse
     */
    @WebMethod(operationName = "FundTransferMobileToAccountInquiry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FundTransferMobileToAccountInquiry", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferMobileToAccountInquiry")
    @ResponseWrapper(localName = "FundTransferMobileToAccountInquiryResponse", targetNamespace = "http://deploy.fasyl.xnett.com/", className = "com.xnett.fasyl.deploy.FundTransferMobileToAccountInquiryResponse")
    @Action(input = "http://deploy.fasyl.xnett.com/Xnett/FundTransferMobileToAccountInquiryRequest", output = "http://deploy.fasyl.xnett.com/Xnett/FundTransferMobileToAccountInquiryResponse")
    public FundTransferMobileToAccountInquiryXResponse fundTransferMobileToAccountInquiry(
        @WebParam(name = "txtBankName", targetNamespace = "")
        String txtBankName,
        @WebParam(name = "txtBranchCode", targetNamespace = "")
        String txtBranchCode,
        @WebParam(name = "txtAccountNumber", targetNamespace = "")
        String txtAccountNumber,
        @WebParam(name = "txtBFName", targetNamespace = "")
        String txtBFName,
        @WebParam(name = "txtBLName", targetNamespace = "")
        String txtBLName,
        @WebParam(name = "txtAmount", targetNamespace = "")
        String txtAmount,
        @WebParam(name = "txtCurrency", targetNamespace = "")
        String txtCurrency,
        @WebParam(name = "txtRefID", targetNamespace = "")
        String txtRefID,
        @WebParam(name = "mydate", targetNamespace = "")
        String mydate,
        @WebParam(name = "txtCountryCode", targetNamespace = "")
        String txtCountryCode,
        @WebParam(name = "txtAuthNum", targetNamespace = "")
        String txtAuthNum,
        @WebParam(name = "txtExternal1", targetNamespace = "")
        String txtExternal1,
        @WebParam(name = "txtExternal2", targetNamespace = "")
        String txtExternal2);

}
