
package t24;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "T24WebServicesImpl", targetNamespace = "http://temenos.com/TWSEFACTURE")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface T24WebServicesImpl {


    /**
     * 
     * @param tnaefacturemainType
     * @param webRequestCommon
     * @param status
     * @param tnaefacturemainType0
     */
    @WebMethod(operationName = "TNAEFACTUREMAIN")
    @RequestWrapper(localName = "TNAEFACTUREMAIN", targetNamespace = "http://temenos.com/TWSEFACTURE", className = "t24.TNAEFACTUREMAIN")
    @ResponseWrapper(localName = "TNAEFACTUREMAINResponse", targetNamespace = "http://temenos.com/TWSEFACTURE", className = "t24.TNAEFACTUREMAINResponse")
    @Action(input = "http://temenos.com/TWSEFACTURE/T24WebServicesImpl/TNAEFACTUREMAINRequest", output = "http://temenos.com/TWSEFACTURE/T24WebServicesImpl/TNAEFACTUREMAINResponse")
    public void tnaefacturemain(
        @WebParam(name = "WebRequestCommon", targetNamespace = "")
        WebRequestCommon webRequestCommon,
        @WebParam(name = "TNAEFACTUREMAINType", targetNamespace = "")
        EnquiryInput tnaefacturemainType,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Status> status,
        @WebParam(name = "TNAEFACTUREMAINType", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<List<TNAEFACTUREMAINType>> tnaefacturemainType0);

}
