
package com.sbs.easymbank.service.omapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "mbInscriptionWsService", targetNamespace = "http://service.ws.mobileBanking.digi/", wsdlLocation = "file:/C:/Users/ALEXAUGUSTE/Documents/EASYMBANK/MTN/MTN/mbInscriptionWs.wsdl")
public class MbInscriptionWsService
    extends Service
{

    private final static URL MBINSCRIPTIONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MBINSCRIPTIONWSSERVICE_EXCEPTION;
    private final static QName MBINSCRIPTIONWSSERVICE_QNAME = new QName("http://service.ws.mobileBanking.digi/", "mbInscriptionWsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/ALEXAUGUSTE/Documents/EASYMBANK/MTN/MTN/mbInscriptionWs.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MBINSCRIPTIONWSSERVICE_WSDL_LOCATION = url;
        MBINSCRIPTIONWSSERVICE_EXCEPTION = e;
    }

    public MbInscriptionWsService() {
        super(__getWsdlLocation(), MBINSCRIPTIONWSSERVICE_QNAME);
    }

    public MbInscriptionWsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MBINSCRIPTIONWSSERVICE_QNAME, features);
    }

    public MbInscriptionWsService(URL wsdlLocation) {
        super(wsdlLocation, MBINSCRIPTIONWSSERVICE_QNAME);
    }

    public MbInscriptionWsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MBINSCRIPTIONWSSERVICE_QNAME, features);
    }

    public MbInscriptionWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MbInscriptionWsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MethodeService
     */
    @WebEndpoint(name = "mbInscriptionWsPort")
    public MethodeService getMbInscriptionWsPort() {
        return super.getPort(new QName("http://service.ws.mobileBanking.digi/", "mbInscriptionWsPort"), MethodeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MethodeService
     */
    @WebEndpoint(name = "mbInscriptionWsPort")
    public MethodeService getMbInscriptionWsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ws.mobileBanking.digi/", "mbInscriptionWsPort"), MethodeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MBINSCRIPTIONWSSERVICE_EXCEPTION!= null) {
            throw MBINSCRIPTIONWSSERVICE_EXCEPTION;
        }
        return MBINSCRIPTIONWSSERVICE_WSDL_LOCATION;
    }

}
